export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS';
export const LOAD_LOGIN_FAIL = 'LOAD_LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
